# Bot settings
bot:
  token: token                # Discord bot token
  prefix: '!'                 # Commands prefix

# Colors
colors:
  error: '0xCB3D35'
  neutral: '0xFFFFFE'
  success: '0x538A1B'

# MySQL database connection
database:
  db: ''
  host: ''
  passwd: ''
  user: ''

# Discord target-guild
guild:
  id: 508721497360171018      # Guild-ID

  # Roles
  roles:
    candidate: 866706203206746153
    player: 866702039466901524
    rejected: 985907462622310410
    spectator: 978723198206099467
    verified: 978723329294872646

  # Channels
  channels:
    # Join-Quit logs channel
    join_logs:
      id: 978724896593027102
      enabled: 1
    
    # Players Profile channel
    players_profile:
      id: 978975750290038794
      enabled: 1

    # Verification info channel
    verification:
      id: 980101976404664440
      enabled: 1

# Minecraft Server settings
mc_server:
  ip: gsprivate.aboba.host                  # Server ip
  nickname_pattern: ^[a-zA-Z0-9_]{2,16}$    # Nickname pattern

  # W-ServerAPI connection
  api:
    host: ''
    port: ''
    token: ''
